torpedo/events/urls.py
'''
Created on 25.8.2012

@author: teerytko
'''

from django.conf.urls import patterns, url, include
from events.feed import EventsFeed

urlpatterns = patterns('',
    # ...
    url(r'^$', 'events.views.events_timeline', name='events_timeline'),
    url(r'^list$', 'events.views.events_list', name='events_list'),
    url(r'^timeline$', 'events.views.events_timeline', name='events_timeline'),
    url(r'^calendar$', 'events.views.events_calendar', name='events_calendar'),
    url(r'^rest', include('events.rest.urls')),
    (r'^feed/(?P<type>[^\/]*)/$', EventsFeed()),
    (r'^feed/$', EventsFeed()),
    #
)

torpedo/statistics/rest/urls.py
'''
Created on 28.6.2012

@author: teerytko
'''

from django.conf.urls import patterns, url
from djangorestframework.resources import ModelResource
from statistics.models import Team, League, Game, Player, Goal, Penalty
from statistics.rest.views import ListSearchModelView, MyInstanceModelView

class StatisticsBaseResource(ModelResource):
    """ Exclude only pk so that id is shown """
    exclude = ('pk')
    allow_unknown_form_fields = True


class TeamResource(StatisticsBaseResource):
    model = Team


class LeagueResource(StatisticsBaseResource):
    model = League


class GameResource(StatisticsBaseResource):
    model = Game
    include = list(StatisticsBaseResource.include) + ['home_goals', 'guest_goals']


class PlayerResource(StatisticsBaseResource):
    model = Player
    include = list(StatisticsBaseResource.include) + ['team_name', 'goals', 'assists',
                                             'penalties', 'points']

class GoalResource(StatisticsBaseResource):
    model = Goal


class PenaltyResource(StatisticsBaseResource):
    model = Penalty


urlpatterns = patterns('',
    url(r'league$', ListSearchModelView.as_view(resource=LeagueResource)),
    url(r'league/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=LeagueResource)),
    url(r'team$', ListSearchModelView.as_view(resource=TeamResource)),
    url(r'team/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=TeamResource)),
    url(r'game$', ListSearchModelView.as_view(resource=GameResource)),
    url(r'game/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=GameResource)),
    url(r'player$', ListSearchModelView.as_view(resource=PlayerResource)),
    url(r'player/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=PlayerResource)),
    url(r'goal$', ListSearchModelView.as_view(resource=GoalResource)),
    url(r'goal/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=GoalResource)),
    url(r'penalty$', ListSearchModelView.as_view(resource=PenaltyResource)),
    url(r'penalty/(?P<pk>[^/]+)/$', MyInstanceModelView.as_view(resource=PenaltyResource)),
)
    

torpedo/statistics/urls.py
'''
Created on 28.6.2012

@author: teerytko
'''

from django.conf.urls import patterns, url, include
urlpatterns = patterns('',
    url(r'(?P<league>\d+)/rest', include('statistics.rest.urls')),
    url(r'(?P<league>\d+)/$', 'statistics.views.statistics', name='statistics'),
    url(r'(?P<league>\d+)/players$', 'statistics.views.players', name='players'),
    url(r'(?P<league>\d+)/game$', 'statistics.views.game', name='game'),
    url(r'(?P<league>\d+)/games$', 'statistics.views.games', name='games'),
    url(r'(?P<league>\d+)/team$', 'statistics.views.team', name='team'),
    url(r'(?P<league>\d+)/teams$', 'statistics.views.teams', name='teams'),
    url(r'/$', 'statistics.views.default'),
)

torpedo/torpedo/urls.py
from django.conf.urls import patterns, include, url
from sitemap import SitemapForum, SitemapTopic
from django.conf import settings
from django.conf.urls.static import static

# from forms import RegistrationFormUtfUsername
#from djangobb_forum import settings as forum_settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

sitemaps = {
    'forum': SitemapForum,
    'topic': SitemapTopic,
}

urlpatterns = patterns('',
    # Examples:

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # Apps
    url(r'^', include('torpedo_main.urls')),
    url(r'^statistics', include('statistics.urls')),

    # Sitemap
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    # Apps
    (r'^forum/', include('djangobb_forum.urls', namespace='djangobb')),
    #(r'^messages/', include('django_messages.urls')),
    (r'^feeds/', include('feedjack.urls')),
    (r'^events/', include('events.urls')),
    # Zinnia blog
    url(r'^weblog/', include('zinnia.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),) 

if settings.SERVE_MEDIA:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

torpedo/statistics/models.py
"""
Statistics model
"""

from datetime import timedelta
from datetime import datetime
from django.db import models
from django.contrib import admin
from django.db.models import Sum


class League(models.Model):
    """
    League is a set of games for a certain period of time.
    """
    name =  models.TextField()
    from_date = models.DateField(null=True, blank=True)
    to_date = models.DateField(null=True, blank=True)

    def __unicode__(self):
        return "%s" % self.name


class Team(models.Model):
    """
    Team is a set of players.
    """
    name =  models.TextField(null=True, blank=True)
    league = models.ForeignKey(League, null=True, blank=True)
    #players = models.ManyToManyField('Player', related_name="teams", null=True, blank=True)

    def __unicode__(self):
        return "Team: %r" % self.name


class Game(models.Model):
    date = models.DateTimeField()
    location = models.TextField(null=True, blank=True)
    home = models.ForeignKey(Team, related_name='home', null=True, blank=True)
    guest = models.ForeignKey(Team, related_name='guest', null=True, blank=True)
    league = models.ForeignKey(League, null=True, blank=True)

    def get_home_name(self):
        return self.home.name

    def set_home_name(self, name):
        home_team = Team.objects.get(name=name)
        self.home = home_team
    home_name = property(get_home_name, set_home_name)

    def get_guest_name(self):
        return self.guest.name

    def set_guest_name(self, name):
        guest_team = Team.objects.get(name=name)
        self.guest = guest_team
    guest_name = property(get_guest_name, set_guest_name)

    @property
    def home_goals(self):
        home_goals = Goal.objects.filter(game=self, team=self.home)
        return home_goals.count()

    @property
    def guest_goals(self):
        return Goal.objects.filter(game=self, team=self.guest).count()

    def __unicode__(self):
        return "Game: %s, %r - %r" % (self.date, self.home, self.guest)

    @property
    def played(self):
        now = datetime.now()
        gamedate = self.date.replace(tzinfo=None)
        return (now-gamedate).total_seconds() > 0

class Player(models.Model):
    number = models.IntegerField(blank=True)
    name = models.TextField(blank=True)
    role= models.TextField(blank=True)
    team=models.ForeignKey(Team, blank=True, null=True)
    league = models.ForeignKey(League, null=True, blank=True)

    @property
    def team_name(self):
        #teams = self.teams.all()
        return self.team.name

    @property
    def goals(self):
        return self.scoring.count()

    @property
    def assists(self):
        return self.assisting.count()

    @property
    def points(self):
        return self.goals + self.assists

    @property
    def penalties(self):
        penalty_time = timedelta()
        for penalty in self.penalty_set.all():
            penalty_time += timedelta(hours=penalty.length.hour,
                                      minutes=penalty.length.minute,
                                      seconds=penalty.length.second,
                                      )
        return penalty_time

    def __unicode__(self):
        return "Player: #%r: %r" % (self.number, self.name)


class Goal(models.Model):
    time = models.TimeField(null=False)
    game = models.ForeignKey(Game)
    team = models.ForeignKey(Team)
    player = models.ForeignKey(Player, related_name='scoring', blank=True, null=True)
    assisting = models.ForeignKey(Player, related_name='assisting', blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    league = models.ForeignKey(League, null=True, blank=True)

    def __unicode__(self):
        return "Goal: %r, %r" % (self.player, self.time)


class Penalty(models.Model):
    time = models.TimeField(null=False)
    length = models.TimeField(null=False) 
    game = models.ForeignKey(Game)
    team = models.ForeignKey(Team)
    player = models.ForeignKey(Player, blank=True, null=True)
    reason = models.IntegerField(blank=True, null=True)
    note = models.TextField(blank=True)
    league = models.ForeignKey(League, null=True, blank=True)

    def __unicode__(self):
        return "Penalty: %r,  %r" % (self.time, self.player)

admin.site.register(League)
admin.site.register(Team)
admin.site.register(Game)
admin.site.register(Player)
admin.site.register(Goal)
admin.site.register(Penalty)

torpedo/statistics/rest/views.py
from djangorestframework.mixins import ListModelMixin, PaginatorMixin, ModelMixin,InstanceMixin, ReadModelMixin, DeleteModelMixin
from djangorestframework.views import InstanceModelView, ListOrCreateModelView, ModelView
from djangorestframework.renderers import BaseRenderer
from statistics.rest.renderers import DListRenderer, DictRenderer
from django.db.models.fields import TextField, CharField
from django.db.models.fields.related import ForeignKey

from django.db.models import Q

class MyUpdateModelMixin(ModelMixin):
    """
    Behavior to update a `model` instance on PUT requests that accepts
    individual field updates
    """
    def put(self, request, *args, **kwargs):
        model = self.resource.model
        if kwargs.has_key('league'):
            kwargs.pop('league')
#             if 'league' in self._resource._model_fields_set:
#                 self.DATA['league'] = League.objects.get(id=lid)
        query_kwargs = self.get_query_kwargs(request, *args, **kwargs)

        # TODO: update on the url of a non-existing resource url doesn't work
        # correctly at the moment - will end up with a new url
        try:
            self.model_instance = self.get_instance(**query_kwargs)
            self.update = self.DATA.dict()
            self.basedata = self.DATA.dict()
            for field in self.model_instance._meta.fields:
                self.basedata.setdefault(field.name, getattr(self.model_instance, field.attname))
            self._content = self.validate_request(self.basedata, self.FILES)
            self.model_instance = self.get_instance(**query_kwargs)
            for (key, val) in self.update.items():
                if key:
                    setattr(self.model_instance, key, val)
        except model.DoesNotExist:
            self.model_instance = model(**self.get_instance_data(model, self.CONTENT, *args, **kwargs))
        self.model_instance.save()
        return self.model_instance

    @property
    def CONTENT(self):
        """
        Returns the cleaned, validated request content.

        May raise an :class:`response.ErrorResponse` with status code 400 (Bad Request).
        """
        if not hasattr(self, '_content'):
            self._content = self.validate_request(self.basedata, self.FILES)
        return self._content

class MyInstanceModelView(InstanceMixin, ReadModelMixin, MyUpdateModelMixin, DeleteModelMixin, ModelView):
    """
    A view which provides default operations for read/update/delete against a model instance.
    """
    renderers = (list(InstanceModelView.renderers) + [DListRenderer])
    _suffix = 'Instance'

    def delete(self, request, *args, **kwargs):
        """
        delete.
        """
        if kwargs.has_key('league'):
            lid = kwargs.pop('league')
            if 'league' in self._resource._model_fields_set and self.DATA is not None:
                self.DATA['league'] = lid
        super(MyInstanceModelView, self).delete(request, *args, **kwargs)

class SearchModelMixin(ListModelMixin, PaginatorMixin):
    """
    Behavior to list a set of `model` instances on GET requests
    """
    def get_query_kwargs(self, request, *args, **kwargs):
        """
        """
        kwargs = request.GET.dict()
        # pop possible echo parameter
        kwargs.pop('sEcho', None)
        # If the URLconf includes a .(?P<format>\w+) pattern to match against
        # a .json, .xml suffix, then drop the 'format' kwarg before
        # constructing the query.
        if BaseRenderer._FORMAT_QUERY_PARAM in kwargs:
            del kwargs[BaseRenderer._FORMAT_QUERY_PARAM]
        return kwargs


class DataTableMixin(ListModelMixin):
    """
    List a set of `model` instances on GET requests based on
    input arguments of DataTables.
    """
    def get_ordering(self):
        return None

    def get_query(self, request, *args, **kwargs):
        """
        Create a query object for the request.

        @param sSearch: search parameter which is searched from all
        TextFields of the model.
        """
        kwargs = request.GET
        query = Q()
        sSearch = kwargs.get('sSearch')
        if sSearch is not None:
            for field in self._resource.model._meta.fields:
                if isinstance(field, TextField) or isinstance(field, CharField):
                    query |=  Q(**{'{0}__{1}'.format(field.attname, 'contains'): sSearch})
                elif isinstance(field, ForeignKey):
                    query |=  Q(**{'{0}__{1}'.format(field.name, 'name__contains'): sSearch})
        sQuery = kwargs.get('sQuery')
        if sQuery is not None:
            queryparams = {}
            for queryitem in sQuery.split(' and '):
                key, value = queryitem.split('==')
                queryparams[key] = value
            query |= Q(**queryparams)
        return query

    def get(self, request, *args, **kwargs):
        """
        Get the data for the request.
        """
        queryset = self.get_queryset()
        self.maxcount = queryset.count()
        if kwargs.has_key('league') and \
        'league' in self._resource._model_fields_set and \
        kwargs['league'] != '0':
            queryset = queryset.filter(league__id=kwargs.get('league'))
        query = self.get_query(request, *args, **kwargs)
        queryset = queryset.filter(query)
        self.totalcount = queryset.count()
        try:
            start = int(request.GET['iDisplayStart'])
            length = int(request.GET['iDisplayLength'])
            if length == -1:
                return queryset
            else:
                return queryset[start:start+length]
        except KeyError:
            return queryset


class ListSearchModelView(DataTableMixin, ListOrCreateModelView):
    """
    A view which provides default operations for searchable list, against a 
    model in the database.
    """
    renderers = (list(InstanceModelView.renderers) + [DListRenderer, DictRenderer])

    _suffix = 'List'

    def post(self, request, *args, **kwargs):
        """
        Create new.
        """
        if kwargs.has_key('league'):
            lid = kwargs.pop('league')
            if 'league' in self._resource._model_fields_set:
                self.DATA['league'] = lid
        resp = super(ListSearchModelView, self).post(request, *args, **kwargs)
        nonfields = set(self.DATA)-set(self.CONTENT)
        instance = resp.raw_content
        for key in nonfields:
            if hasattr(instance, key):
                getattr(instance, key).add(self.DATA[key])
        return resp

torpedo/statistics/templates/statistics/base.html
{% extends 'torpedo/fixedbase.html' %}
{% block head_addition %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/table.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/tables_page.css">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> 
{% block head_datatables %}
{% endblock %}
{% endblock %}

torpedo/statistics/templates/statistics/breadcrumb.html
{% load i18n %}

<ol class="breadcrumb">
  {% for key, mainitem in breadcrumbs.items %}
    <li class="btn-group"
    {% if mainitem.children %}class="dropdown"{% endif %}>
    <a id="link-{{key}}" href="{{mainitem.href}}">{{ mainitem.name }}</a>
        {% if mainitem.children %}
        <a class="dropdown-toggle" data-toggle="dropdown" 
        href="#"><span class="caret"></span>
        </a>
        {% endif %}
        {% if mainitem.children %}
          <ul class='dropdown-menu'>
          {% for subitem in mainitem.children.values %}
            <li><a href="{{subitem.href}}">{{ subitem.name }}</a></li>
          {% endfor %}
          </ul>
        {% endif %}
    </li>
  {% endfor %}
</ol>

torpedo/statistics/templates/statistics/game.html
{% extends 'statistics/base.html' %}
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
{% block head_datatables %}
{% endblock %}

{% block main %}
{% include 'statistics/breadcrumb.html' %}
    <div class="full_width big">
        <i><div id="game-info"></div></i>
    </div>
    
    <p>Peli tietojen täyttö</p>
    <div id="dynamic">  
    <table class="display">
    <tr><td colspan="2">
        <!-- pelin perustiedot -->
        <table cellpadding="0" cellspacing="0" border="0" width="100%" id="salibandy_game">
        <thead>
            <tr>
                <th width="0%">Id</th>
                <th width="20%">Aika</th>
                <th width="15%">Paikka</th>
                <th width="25%">Koti</th>
                <th width="25%">Koti</th>
                <th width="25%">Vieras</th>
                <th width="25%">Vieras</th>
                <th width="25%">Koti maalit</th>
                <th width="25%">Vieras maalit</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="9"></td>
            </tr>
        </tbody>
        </table>
    </td></tr>
    <tr><td>
 
        <!--<table cellpadding="0" cellspacing="0" border="0" id="content">-->
        <tr>
            <th width="50%">Maalit</th>
            <th width="50%">Rangaistukset</th>
        </tr>
        <tr>
            <td colspan="2"><div id="home-team-info"></div></td>
        </tr>
        {% if perms.statistics.change_game %}
        <tr>
            <td colspan="1">
                <a href="javascript:void(0);" id="add-homeGoal" style="color:black">Lisää</a> / 
                <a href="javascript:void(0);" id="delete-homeGoal" style="color:black">Poista</a> /
                <a href="javascript:void(0);" id="edit-homeGoal" style="color:black">Muokkaa</a>
            </td>
            <td colspan="1">
                <a href="javascript:void(0);" id="add-homePenalty" style="color:black">Lisää</a> / 
                <a href="javascript:void(0);" id="delete-homePenalty" style="color:black">Poista</a> /
                <a href="javascript:void(0);" id="edit-homePenalty" style="color:black">Muokkaa</a>
            </td>
        </tr>
        {% endif %}
        <tr>
            <td>
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="homegoal">
                <thead>
                    <tr>
                        <th width="0%">Id</th>
                        <th width="10%">Aika</th>
                        <th width="40%">Tekijä</th>
                        <th width="40%">Syöttäjä</th>
                        <th width="10%">Koodi</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="5">null</td>
                    </tr>
                </tbody>
            </table>
            </td>    
            <td>
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="homepenalty">
                <thead>
                    <tr>
                        <th width="0%">Id</th>
                        <th width="10%">Aika</th>
                        <th width="10%">Kesto</th>
                        <th width="50%">Pelaaja</th>
                        <th width="5%">Syy</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="5">null</td>
                    </tr>
                </tbody>
            </table>
            </td>    
        </tr>
        <tr>
            <td colspan="2"><div id="guest-team-info"></div></td>
        </tr>
        {% if perms.statistics.change_game %}
        <tr>
            <td colspan="1">
                <a href="javascript:void(0);" id="add-guestGoal" style="color:black">Lisää</a> / 
                <a href="javascript:void(0);" id="delete-guestGoal" style="color:black">Poista</a> /
                <a href="javascript:void(0);" id="edit-guestGoal" style="color:black">Muokkaa</a>
            </td>
            <td colspan="1">
                <a href="javascript:void(0);" id="add-guestPenalty" style="color:black">Lisää</a> / 
                <a href="javascript:void(0);" id="delete-guestPenalty" style="color:black">Poista</a> /
                <a href="javascript:void(0);" id="edit-guestPenalty" style="color:black">Muokkaa</a>
            </td>
        </tr>
        {% endif %}
        <tr>
            <td>
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="guestgoal">
                <thead>
                    <tr>
                        <th width="0%">Id</th>
                        <th width="10%">Aika</th>
                        <th width="30%">Tekijä</th>
                        <th width="30%">Syöttäjä</th>
                        <th width="10%">Koodi</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="5">null</td>
                    </tr>
                </tbody>
            </table>
            </td>    
            <td>
            <table cellpadding="0" cellspacing="0" border="0" class="display" id="guestpenalty">
                <thead>
                    <tr>
                        <th width="0%">Id</th>
                        <th width="10%">Aika</th>
                        <th width="10%">Kesto</th>
                        <th width="50%">Pelaaja</th>
                        <th width="5%">Syy</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="5">null</td>
                    </tr>
                </tbody>
            </table>
            </td>    
        </tr>
        <!--</table> -->
        
        </td>    
    </tr>
    </table>
</div>
{% endblock %}

{% block scripts %}
<script>var SOURCEROOT="{{source}}";</script>
<script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/game.view.js" type="text/javascript"></script>
{% endblock %}

torpedo/statistics/templates/statistics/games.html
{% extends 'statistics/base.html' %}
{% block head_datatables %}    
{% endblock %}

{% block main %}
{% include 'statistics/breadcrumb.html' %}

    {% if user.is_authenticated %}
    <button type="button" id="add-game-btn">Add game</button>
    {% endif %}
<table cellpadding="0" cellspacing="0" border="0" class="display" id="pelit">
<thead>
    <tr>
        <th width="10%">Id</th>
        <th width="20%">Aika</th>
        <th width="15%">Paikka</th>
        <th width="25%">Koti</th>
        <th width="25%">Vieras</th>
        <th width="25%">Koti maalit</th>
        <th width="25%">Vieras maalit</th>
    </tr>
</thead>
<tbody>
    <tr>
        <td colspan="7"></td>
    </tr>
</tbody>
</table>
{% endblock %}

{% block scripts %}
<script>var SOURCEROOT="{{source}}";</script>
<script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/games.view.js" type="text/javascript"></script>
{% endblock %}

torpedo/statistics/templates/statistics/main.html
{% extends 'statistics/base.html' %}
{% block head_datatables %} 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> 
{% endblock %}

{% block main %}
{% include 'statistics/breadcrumb.html' %}

<table cellpadding="0" cellspacing="0" border="0" class="display" id="players">
    <thead>
        <tr>
            <th width="0%">Id</th>
            <th width="15%">Pelaaja</th>
            <th width="15%">Nimi</th>
            <th width="20%">Joukkue</th>
            <th width="5%">Maalit</th>
            <th width="5%">Syötöt</th>
            <th width="5%">Pisteet</th>
            <th width="5%">Jäähyt</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="8">null</td>
        </tr>
    </tbody>
</table>
{% endblock %}
{% block scripts %}
<script>var SOURCEROOT="{{source}}";</script>
<script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/main.view.js" type="text/javascript"></script>
{% endblock %}

torpedo/statistics/templates/statistics/team.html
{% extends 'statistics/base.html' %}
{% load i18n %}
{% block head_datatables %}
{% endblock %} 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

{% block main %}
{% include 'statistics/breadcrumb.html' %}
    <div class="full_width big">
        <i><div id="team-name"></div></i>
        </div>
    <div id="dynamic">
    <!-- joukkeen pelaajat -->
    <h2>Pelaajat</h2>
    <p>
        <a href="./teams">Takaisin joukkueisiin</a>
        {% if perms.statistics.change_game %}
        /
        <a data-url="/statistics/" id="add">Lisää</a>
        /
        <a id="delete">Poista</a>
        /
        <a id="edit">Muokkaa</a>
        {% endif %}
    </p>
    <table cellpadding="0" cellspacing="0" border="0" class="display" id="players">
        <thead>
            <tr>
                <th width="10%">Id</th>
                <th width="15%">Team_id</th>
                <th width="20%">Number</th>
                <th width="50%">Name</th>
                <th width="50%">Rooli</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>null</td>
                <td>null</td>
            </tr>
        </tbody>
    </table>
    </div>

<!-- Modal -->
<div class="modal fade" id="addPlayerModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add player</h4>
      </div>
      <div class="modal-body">
        <div class="container">
          Lisää uusi pelaaja tai kopio olemassa oleva.
          <div class="input-group">
            <div class="input-group-btn">
                <button id="selected-player" data-selected='new' type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">New <span class="caret"></span></button>
                <ul id="selectable-players" class="dropdown-menu">
                    <li><a class="drp-btn" href="#">Dummy</a></li>
                </ul>
            </div><!-- /btn-group -->
          </div><!-- /input-group -->
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" id="dlg-add-player" class="btn btn-primary">Add</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


{% endblock %}

{% block scripts %}
<script>var SOURCEROOT="{{source}}";</script>
<script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/team.view.js" type="text/javascript"></script>
{% endblock %}

torpedo/statistics/templates/statistics/teams.html
{% extends 'statistics/base.html' %}
{% block head_datatables %}
{% endblock %}


{% block main %}
{% include 'statistics/breadcrumb.html' %}

{% if perms.statistics.change_game %}
<button type="button" id="add-team-btn">Add team</button>
{% endif %}

<table class="display" id="teams">
  <thead>
    <tr>
      <th width="10%">Id</th>
      <th width="20%">Nimi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="2">null</td>
     </tr>
  </tbody>
</table>
{% endblock %}

{% block scripts %}
<script>var SOURCEROOT="{{source}}";</script>
<script src="{{ STATIC_URL }}js/statistics.config.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/teams.view.js" type="text/javascript"></script>
{% endblock %}